
export const barChartsVertical = [
    {
        name: 'Vertical Bar Chart',
        selector: 'bar-vertical',
        inputFormat: 'singleSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'refLines',
            'showRefLines',
            'showRefLabels',
            'roundEdges',
            'yScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ]
    },
    {
        name: 'Grouped Vertical Bar Chart',
        selector: 'bar-vertical-2d',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'groupPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'roundEdges',
            'yScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ]
    },
    {
        name: 'Stacked Vertical Bar Chart',
        selector: 'bar-vertical-stacked',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'yScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ]
    },
    {
        name: 'Normalized Vertical Bar Chart',
        selector: 'bar-vertical-normalized',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Normalized GDP Per Capita',
            xAxisLabel: 'Country'
        }
    }
];
