
export const barChartsHorizontal = [
    {
        name: 'Horizontal Bar Chart',
        selector: 'bar-horizontal',
        inputFormat: 'singleSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'refLines',
            'showRefLines',
            'showRefLabels',
            'roundEdges',
            'xScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Country',
            xAxisLabel: 'GDP Per Capita'
        }
    },
    {
        name: 'Grouped Horizontal Bar Chart',
        selector: 'bar-horizontal-2d',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'groupPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'roundEdges',
            'xScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Country',
            xAxisLabel: 'GDP Per Capita'
        }
    },
    {
        name: 'Stacked Horizontal Bar Chart',
        selector: 'bar-horizontal-stacked',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'xScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Country',
            xAxisLabel: 'GDP Per Capita'
        }
    },
    {
        name: 'Normalized Horizontal Bar Chart',
        selector: 'bar-horizontal-normalized',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Country',
            xAxisLabel: 'Normalized GDP Per Capita'
        }
    }
];
