
export const demosAdvanced = [
    {
        name: 'Tooltip Templates',
        selector: 'tooltip-templates',
        inputFormat: 'singleSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled'
        ]
    },
    {
        name: 'Sparklines',
        selector: 'sparkline',
        inputFormat: 'multiSeries',
        options: ['animations', 'curve']
    },
    {
        name: 'Line Chart with Reference Lines',
        selector: 'line-reference-lines',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'timeline',
            'showGridLines',
            'curve',
            'rangeFillOpacity',
            'roundDomains',
            'tooltipDisabled',
            'showRefLines',
            'referenceLines',
            'showRefLabels',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength'
        ],
        defaults: {
            yAxisLabel: 'GDP Per Capita',
            xAxisLabel: 'Year',
            linearScale: false
        }
    },
    {
        name: 'Timeline Filter Bar Chart',
        selector: 'timeline-filter-bar-chart-demo',
        inputFormat: 'timelineFilter',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'noBarWhenZero',
            'gradient',
            'showGridLines',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel'
        ]
    },
    {
        name: 'Stacked Vertical Bar Chart Negative',
        selector: 'bar-vertical-stacked-negative',
        inputFormat: 'multiSeriesNegative',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'barPadding',
            'noBarWhenZero',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'yScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength'
        ]
    },
    {
        name: 'Stacked Horizontal Bar Chart Negative',
        selector: 'bar-horizontal-stacked-negative',
        inputFormat: 'multiSeriesNegative',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'noBarWhenZero',
            'barPadding',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'showGridLines',
            'roundDomains',
            'tooltipDisabled',
            'yScaleMax',
            'showDataLabel',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength'
        ]
    }
];
