
export const lineAreaCharts = [
    {
        name: 'Line Chart',
        selector: 'line-chart',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'timeline',
            'showGridLines',
            'curve',
            'rangeFillOpacity',
            'roundDomains',
            'tooltipDisabled',
            'showRefLines',
            'referenceLines',
            'showRefLabels',
            'xScaleMin',
            'xScaleMax',
            'yScaleMin',
            'yScaleMax',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'GDP Per Capita',
            xAxisLabel: 'Census Date',
            linearScale: true
        }
    },
    {
        name: 'Polar Chart',
        selector: 'polar-chart',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'showGridLines',
            'curveClosed',
            'roundDomains',
            'tooltipDisabled',
            'trimYAxisTicks',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'GDP Per Capita',
            xAxisLabel: 'Census Date',
            linearScale: true
        }
    },
    {
        name: 'Area Chart',
        selector: 'area-chart',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'timeline',
            'showGridLines',
            'curve',
            'roundDomains',
            'tooltipDisabled',
            'refLinesArea',
            'showRefLines',
            'showRefLabels',
            'xScaleMin',
            'xScaleMax',
            'yScaleMin',
            'yScaleMax',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'GDP Per Capita',
            xAxisLabel: 'Census Date',
            linearScale: true
        }
    },
    {
        name: 'Stacked Area Chart',
        selector: 'area-chart-stacked',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'timeline',
            'showGridLines',
            'curve',
            'roundDomains',
            'tooltipDisabled',
            'xScaleMin',
            'xScaleMax',
            'yScaleMin',
            'yScaleMax',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'GDP Per Capita',
            xAxisLabel: 'Census Date',
            linearScale: true
        }
    },
    {
        name: 'Normalized Area Chart',
        selector: 'area-chart-normalized',
        inputFormat: 'multiSeries',
        options: [
            'animations',
            'colorScheme',
            'schemeType',
            'showXAxis',
            'showYAxis',
            'gradient',
            'showLegend',
            'legendTitle',
            'legendPosition',
            'showXAxisLabel',
            'xAxisLabel',
            'showYAxisLabel',
            'yAxisLabel',
            'autoScale',
            'timeline',
            'showGridLines',
            'curve',
            'roundDomains',
            'tooltipDisabled',
            'trimXAxisTicks',
            'trimYAxisTicks',
            'rotateXAxisTicks',
            'maxXAxisTickLength',
            'maxYAxisTickLength',
            'wrapTicks'
        ],
        defaults: {
            yAxisLabel: 'Normalized GDP Per Capita',
            xAxisLabel: 'Census Date',
            linearScale: true
        }
    }
];
